"""initia32

Revision ID: 8561189d8e71
Revises: 5077129d5b98
Create Date: 2025-09-19 02:33:22.239974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8561189d8e71'
down_revision = '5077129d5b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('git_link', sa.String(length=200), nullable=True),
    sa.Column('hosted_link', sa.String(length=200), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
