"""initial2

Revision ID: b221e53b3117
Revises: 
Create Date: 2025-09-19 02:29:11.483720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b221e53b3117'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('git_link', sa.String(length=200), nullable=True),
    sa.Column('hosted_link', sa.String(length=200), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
